apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 00-role.yaml
- 00-account.yaml
- 01-role-binding.yaml
- 02-traefik.yaml
- 02-traefik-services.yaml
- nginx/nginx-deployment.yaml
- nginx/ingress.yaml